export const data = [
  {
    id: 1,
    category: "lunch",
    img: "https://i.ibb.co/2h9WR2Z/lunch6.png",
    title: "Healthy Meal Plan",
    text: "Stay healthy, Eat healthy",
    price: "23.99",
  },
  {
    id: 2,
    category: "lunch",
    img: "https://i.ibb.co/fXybM2W/lunch5.png",
    title: "Fried Chicken Bento",
    text: "Stay healthy, Eat healthy",
    price: "9.99",
  },
  {
    id: 3,
    category: "lunch",
    img: "https://i.ibb.co/dQZMDBm/lunch4.png",
    title: "Tarrangon-Rubbed-Salmon",
    text: "Stay healthy, Eat healthy",
    price: "6.99",
  },
  {
    id: 4,
    category: "lunch",
    img: "https://i.ibb.co/M5DLmvz/lunch3.png",
    title: "Indian Lunch",
    text: "Stay healthy, Eat healthy",
    price: "8.99",
  },
  {
    id: 5,
    category: "lunch",
    img: "https://i.ibb.co/rpK9X6d/lunch1.png",
    title: "Beef Steak",
    text: "Stay healthy, Eat healthy",
    price: "15.99",
  },
  {
    id: 6,
    category: "lunch",
    img: "https://i.ibb.co/d7ykRXd/lunch2.png",
    title: "Honey-Soy-Glazed Salmon with Peppers",
    text: "Stay healthy, Eat healthy",
    price: "7.99",
  },
  {
    id: 7,
    category: "breakfast",
    img: "https://i.ibb.co/4PGWr1f/breakfast6.png",
    title: "Bagel and cream cheese",
    text: "Stay healthy, Eat healthy",
    price: "6.99",
  },
  {
    id: 8,
    category: "breakfast",
    img: "https://i.ibb.co/4tvq9nc/breakfast5.png",
    title: "Breakfast sandwich",
    text: "Stay healthy, Eat healthy",
    price: "9.99",
  },
  {
    id: 9,
    category: "breakfast",
    img: "https://i.ibb.co/xGgK8KL/breakfast4.png",
    title: "Baked chicken",
    text: "Stay healthy, Eat healthy",
    price: "10.99",
  },
  {
    id: 10,
    category: "breakfast",
    img: "https://i.ibb.co/cQsJ8g9/breakfast3.png",
    title: "Eggs Benedict",
    text: "Stay healthy, Eat healthy",
    price: "8.99",
  },
  {
    id: 11,
    category: "breakfast",
    img: "https://i.ibb.co/XshjGbZ/breakfast2.png",
    title: "Toast Croissant Fried Egg",
    text: "Stay healthy, Eat healthy",
    price: "19.99",
  },
  {
    id: 12,
    category: "breakfast",
    img: "https://i.ibb.co/L09LGYw/breakfast1.png",
    title: "Full Breakfast Fried Egg Toast Brunch",
    text: "Stay healthy, Eat healthy",
    price: "3.99",
  },
  {
    id: 13,
    category: "dinner",
    img: "https://i.ibb.co/sQ5bj72/dinner1.png",
    title: "Salmon with grapefruit and Lentil salad",
    text: "Stay healthy, Eat healthy",
    price: "9.99",
  },
  {
    id: 14,
    category: "dinner",
    img: "https://i.ibb.co/GcqwJS2/dinner6.png",
    title: "Lemony Salmon Piccata",
    text: "Stay healthy, Eat healthy",
    price: "10.99",
  },
  {
    id: 15,
    category: "dinner",
    img: "https://i.ibb.co/tsmPrKb/dinner5.png",
    title: "Beef Tendeloin With Quinoa pilag",
    text: "Stay healthy, Eat healthy",
    price: "12.99",
  },
  {
    id: 16,
    category: "dinner",
    img: "https://i.ibb.co/Px0yTCF/dinner4.png",
    title: "French fries with cheese",
    text: "Stay healthy, Eat healthy",
    price: "8.99",
  },
  {
    id: 17,
    category: "dinner",
    img: "https://i.ibb.co/1vS1Zyt/dinner2.png",
    title: "Garlic Butter Baked Salmon",
    text: "Stay healthy, Eat healthy",
    price: "6.99",
  },
  {
    id: 18,
    category: "dinner",
    img: "https://i.ibb.co/QHRxG48/dinner3.png",
    title: "Baked Chicken",
    text: "Stay healthy, Eat healthy",
    price: "9.99",
  },
];
